### ISSUE TITLE
English suggestion on this line of the README

### ISSUE THREAD

**Issue by JesusMurF** [mugan86/ng-leaflet#10]
https://github.com/mugan86/ng-leaflet/blob/0b021b1ba77785aa3063ad8da48bd725eab23b31/README.md?plain=1#L33

If I were you I would change "Use references" to "References", I think is cleaner and clearer. 😊

**Comment by mugan86** [comment]
I totally agree with what you say, Jesus, although this document is a draft. I will update and take that point into account, although I am considering not putting those sources and having them for myself and people that I think are appropriate, as would be your case. Thanks machine ;)

**Comment by JesusMurF** [comment]
It will be our secret 🤫😁

**Comment by mugan86** [comment]
👍  Thanks!

**Comment by mugan86** [comment]
I add this info in next URL: https://github.com/mugan86/ng-leaflet/wiki/Interesting-References after remove from start README.md. Close issue, thanks Jesus!
